require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const connectDB = require('../config/db');
const Section = require('../models/Section');

async function seedSections() {
  await connectDB();
  await Section.deleteMany({});

  const homeSections = [
    { pageName: 'home', sectionKey: 'hero', order: 1, title: 'One Stop Solution for VCI & Seaworthy Packaging', subtitle: 'Protecting Your Products from Corrosion, Moisture & Transit Damage', description: 'Sharma Packaging delivers premium VCI products, seaworthy packing, and export packaging solutions from Vadodara, Gujarat. Trusted by 100+ industrial clients.', buttons: [{ text: 'Explore Products', link: '/products', style: 'primary' }, { text: 'Get Quote', link: '/contact-us', style: 'secondary' }, { text: 'Contact Us', link: '/contact-us', style: 'outline' }] },
    { pageName: 'home', sectionKey: 'trust-badges', order: 2, title: 'Trusted by Industries Across India', contentBlocks: [{ title: 'VCI Products', icon: 'FaShieldAlt' }, { title: 'Export Packaging', icon: 'FaGlobeAmericas' }, { title: 'Seaworthy Packing', icon: 'FaShip' }, { title: 'Custom Solutions', icon: 'FaCogs' }, { title: 'Gujarat Manufacturer', icon: 'FaIndustry' }] },
    { pageName: 'home', sectionKey: 'about-preview', order: 3, title: 'About Sharma Packaging', subtitle: 'Your Trusted Packaging Partner in Vadodara', description: 'Sharma Packaging is a trusted provider of custom-made VCI products and seaworthy packaging solutions in Vadodara, Gujarat. We help industries protect products from corrosion, moisture, handling damage, and export transit risk. With expertise in VCI film, aluminium barrier foil, humidity indicators, silpaulin covers, shrink packing, heavy duty protective covers, and cargo project packing.', buttons: [{ text: 'Read More', link: '/about-us', style: 'primary' }] },
    { pageName: 'home', sectionKey: 'why-choose-us', order: 4, title: 'Why Choose Sharma Packaging?', subtitle: 'Custom-made packaging solutions that resolve corrosion problems while increasing profitability', contentBlocks: [{ title: 'Custom Packing Solutions', description: 'Tailored packaging designed for your specific product requirements.', icon: 'FaBoxOpen' }, { title: 'Customer Satisfaction', description: 'Dedicated to exceeding client expectations with every project.', icon: 'FaSmile' }, { title: 'Corrosion Protection', description: 'Advanced VCI technology for complete metal protection.', icon: 'FaShieldAlt' }, { title: 'Export Ready Packaging', description: 'International standard compliant packaging for global shipments.', icon: 'FaGlobeAmericas' }, { title: 'Industrial Grade Material', description: 'Premium quality materials for maximum protection and durability.', icon: 'FaIndustry' }, { title: 'Cost Effective Solutions', description: 'Optimized packaging that reduces costs without compromising quality.', icon: 'FaRupeeSign' }] },
    { pageName: 'home', sectionKey: 'product-categories', order: 5, title: 'Our Product Range', subtitle: 'Premium VCI & Industrial Packaging Products' },
    { pageName: 'home', sectionKey: 'more-products', order: 6, title: 'More Products', subtitle: 'Complete Range of Industrial Packaging Solutions' },
    { pageName: 'home', sectionKey: 'specialization', order: 7, title: 'Our Specialization', subtitle: 'Areas of Expertise', contentBlocks: [{ title: 'VCI film & Aluminium Barrier Foil Rolls and Covers.' }, { title: 'Desiccants and Humidity Indicator.' }, { title: 'Tarpaulin & Silpaulin Rolls and Covers.' }, { title: 'Seaworthy Packing' }, { title: 'ODC and Cargo Project Packing' }, { title: 'Packing Consultancy' }] },
    { pageName: 'home', sectionKey: 'industries', order: 8, title: 'Industries We Serve', subtitle: 'Trusted by Leading Industries', contentBlocks: [{ title: 'Engineering Industry', icon: 'FaCogs' }, { title: 'Automotive Industry', icon: 'FaCar' }, { title: 'Electronics Industry', icon: 'FaMicrochip' }, { title: 'Ceramic Products', icon: 'FaCubes' }, { title: 'Machinery Exporters', icon: 'FaTruckLoading' }, { title: 'Chemical Industry', icon: 'FaFlask' }, { title: 'Defence & Heavy Equipment', icon: 'FaShieldAlt' }, { title: 'Logistics & Warehousing', icon: 'FaWarehouse' }, { title: 'Marine Export', icon: 'FaShip' }, { title: 'Industrial Manufacturers', icon: 'FaIndustry' }] },
    { pageName: 'home', sectionKey: 'seaworthy', order: 9, title: 'Seaworthy Packing Solutions', subtitle: 'Protecting Your Cargo for Ocean Transit', description: 'Our seaworthy packing solutions protect your valuable export cargo from moisture, corrosion, vibration, and physical damage during ocean freight. We use multi-layer protection systems including VCI films, desiccants, aluminium barrier foils, and engineered crating.', buttons: [{ text: 'Request Quote', link: '/contact-us', style: 'primary' }] },
    { pageName: 'home', sectionKey: 'vci-packaging', order: 10, title: 'VCI Packaging Solutions', subtitle: 'Advanced Corrosion Protection for Metal Components', description: 'Our VCI (Volatile Corrosion Inhibitor) packaging products provide active corrosion protection for ferrous and non-ferrous metals. VCI molecules create an invisible protective layer that prevents oxidation during storage and transit, eliminating the need for messy oils and greases.' },
    { pageName: 'home', sectionKey: 'export-process', order: 11, title: 'Export Packaging Process', subtitle: 'Our Systematic Approach', contentBlocks: [{ title: 'Requirement Analysis', description: 'Understanding your product and export requirements', icon: 'FaClipboardList' }, { title: 'Material Selection', description: 'Choosing optimal packaging materials', icon: 'FaBoxes' }, { title: 'Custom Packing', description: 'Engineered packaging execution', icon: 'FaTools' }, { title: 'Quality Check', description: 'Rigorous quality inspection', icon: 'FaCheckCircle' }, { title: 'Dispatch Support', description: 'Logistics and dispatch coordination', icon: 'FaTruck' }] },
    { pageName: 'home', sectionKey: 'defence-packaging', order: 12, title: 'Defence & Heavy Machinery Packaging', subtitle: 'Specialized Packaging for Critical Equipment', description: 'We provide specialized packaging solutions for defence equipment, heavy machinery, project cargo, and industrial equipment. Our packaging ensures complete protection during handling, storage, and long-distance transportation.' },
    { pageName: 'home', sectionKey: 'gallery-preview', order: 13, title: 'Our Work Gallery', subtitle: 'See Our Packaging Solutions in Action', buttons: [{ text: 'View Full Gallery', link: '/gallery', style: 'primary' }] },
    { pageName: 'home', sectionKey: 'certifications', order: 14, title: 'Quality & Certifications', subtitle: 'Committed to Excellence', contentBlocks: [{ title: 'Quality Commitment', description: 'Stringent quality control at every stage of production', icon: 'FaAward' }, { title: 'Industrial Grade Material', description: 'Premium raw materials from trusted suppliers', icon: 'FaGem' }, { title: 'Export-Focused Packaging', description: 'International standard compliance for global shipments', icon: 'FaGlobe' }, { title: 'Safety-First Approach', description: 'Prioritizing safety in every packaging solution', icon: 'FaHardHat' }] },
    { pageName: 'home', sectionKey: 'process', order: 15, title: 'Our Process', subtitle: 'From Consultation to Dispatch', contentBlocks: [{ title: 'Consultation', description: 'Understanding your packaging needs', icon: 'FaComments' }, { title: 'Packaging Design', description: 'Engineering the optimal solution', icon: 'FaDraftingCompass' }, { title: 'Material Preparation', description: 'Sourcing and preparing materials', icon: 'FaLayerGroup' }, { title: 'Packing Execution', description: 'Professional packing execution', icon: 'FaHammer' }, { title: 'Final Dispatch', description: 'Quality check and dispatch', icon: 'FaShippingFast' }] },
    { pageName: 'home', sectionKey: 'statistics', order: 16, title: 'Our Impact in Numbers', contentBlocks: [{ title: '500+', description: 'Packaging Projects' }, { title: '100+', description: 'Industrial Clients' }, { title: '10+', description: 'Product Categories' }, { title: '15+', description: 'Years Experience' }] },
    { pageName: 'home', sectionKey: 'client-satisfaction', order: 17, title: 'Client Satisfaction', subtitle: 'Why Our Clients Trust Us', contentBlocks: [{ title: 'Timely Delivery', description: 'On-time project completion every time', icon: 'FaClock' }, { title: 'Reliable Packaging', description: 'Consistent quality and protection', icon: 'FaThumbsUp' }, { title: 'Custom Solutions', description: 'Tailored to your exact requirements', icon: 'FaPuzzlePiece' }, { title: 'Dedicated Support', description: '24/7 customer support and guidance', icon: 'FaHeadset' }] },
    { pageName: 'home', sectionKey: 'blog-preview', order: 18, title: 'Latest From Our Blog', subtitle: 'Industry Insights & Packaging Tips', buttons: [{ text: 'View More Blogs', link: '/blog', style: 'primary' }] },
    { pageName: 'home', sectionKey: 'faq', order: 19, title: 'Frequently Asked Questions', subtitle: 'Common Questions About Our Packaging Solutions' },
    { pageName: 'home', sectionKey: 'final-cta', order: 20, title: 'Need Reliable VCI & Seaworthy Packaging in Vadodara?', subtitle: 'Get in touch with our packaging experts today', buttons: [{ text: 'Call Now', link: 'tel:+917383411611', style: 'primary' }, { text: 'WhatsApp', link: 'https://wa.me/917383411611', style: 'secondary' }, { text: 'Get Quote', link: '/contact-us', style: 'outline' }] },
  ];

  const aboutSections = [
    { pageName: 'about', sectionKey: 'hero', order: 1, title: 'About Sharma Packaging', subtitle: 'Your Trusted Industrial Packaging Partner Since 2009' },
    { pageName: 'about', sectionKey: 'introduction', order: 2, title: 'Company Introduction', description: 'Sharma Packaging is a trusted provider of custom-made VCI products and seaworthy packaging solutions in Vadodara, Gujarat. The company helps industries protect products from corrosion, moisture, handling damage, and export transit risk. With expertise in VCI film, aluminium barrier foil, humidity indicators, silpaulin covers, shrink packing, heavy duty protective covers, and cargo project packing, Sharma Packaging delivers reliable industrial packaging support for manufacturers and exporters.' },
    { pageName: 'about', sectionKey: 'mission-vision', order: 3, title: 'Mission & Vision', contentBlocks: [{ title: 'Our Mission', description: 'To provide world-class packaging solutions that protect products, reduce costs, and enable businesses to grow their export capabilities with confidence.' }, { title: 'Our Vision', description: 'To be the most trusted and innovative industrial packaging company in Gujarat, setting new standards for quality, reliability, and customer satisfaction.' }] },
    { pageName: 'about', sectionKey: 'why-us', order: 4, title: 'Why Sharma Packaging?', description: 'Sharma Packaging provides custom-made packaging solutions that resolve corrosion problems while increasing company profitability by reducing operating costs, increasing process yields, and enhancing customer satisfaction.' },
    { pageName: 'about', sectionKey: 'quality', order: 5, title: 'Quality Commitment', description: 'Quality is the cornerstone of everything we do. From raw material selection to final packaging delivery, every step is monitored and controlled to ensure the highest standards of performance and protection.' },
    { pageName: 'about', sectionKey: 'expertise', order: 6, title: 'Our Expertise', contentBlocks: [{ title: 'VCI Technology' }, { title: 'Seaworthy Packing' }, { title: 'Aluminium Barrier Solutions' }, { title: 'Export Packaging' }, { title: 'Heavy Machinery Packaging' }, { title: 'Consultancy Services' }] },
    { pageName: 'about', sectionKey: 'infrastructure', order: 7, title: 'Manufacturing Infrastructure', description: 'Our state-of-the-art manufacturing facility in GIDC Makarpura, Vadodara is equipped with modern machinery and technology to produce high-quality packaging materials efficiently and at scale.' },
    { pageName: 'about', sectionKey: 'cta', order: 8, title: 'Partner with Sharma Packaging', subtitle: 'Let us help protect your products and grow your business', buttons: [{ text: 'Contact Us Today', link: '/contact-us', style: 'primary' }] },
  ];

  const contactSections = [
    { pageName: 'contact', sectionKey: 'hero', order: 1, title: 'Contact Us', subtitle: 'Get in Touch with Our Packaging Experts' },
    { pageName: 'contact', sectionKey: 'info', order: 2, title: 'Contact Information', contentBlocks: [{ title: 'Address', description: '253/19-A, Opp. Columbia Machine Pvt Ltd, GIDC Industrial Estate, Makarpura, Vadodara - 390010, Gujarat', icon: 'FaMapMarkerAlt' }, { title: 'Phone', description: '+91 7384 11611', icon: 'FaPhone' }, { title: 'Email', description: 'vijay@sharmapackagings.com', icon: 'FaEnvelope' }, { title: 'Business Hours', description: 'Monday - Saturday: 9:00 AM - 6:00 PM', icon: 'FaClock' }] },
  ];

  await Section.insertMany([...homeSections, ...aboutSections, ...contactSections]);
  console.log('✅ Sections seeded');
  process.exit(0);
}
seedSections().catch(e => { console.error(e); process.exit(1); });
